### ISSUE TITLE
[FEATURE] Add ExeterGUI module

### ISSUE THREAD

**Issue by Joao0464** [Ai2473/3arthh4ck#18]
![images](https://user-images.githubusercontent.com/115934609/234379342-150a6ad5-d163-4c39-8553-a341edf023d9.jpeg)
This module would make it as similar as possible to FutureClient in a simple way, just adding gears next to the name of all modules and when opening the configuration of a module, rotate it, the same happening in the original client.

**Comment by Ai2473** [comment]
i could make a plugin, but i won't add this to the main client

**Comment by Joao0464** [comment]
> i could make a plugin, but i won't add this to the main client

Where will it be available for download

**Comment by EndCrystal-MC** [comment]
would be really cool as a plugin for those who want to use it!

**Comment by Ai2473** [comment]
done as plugin, release will be in a few days
